---
- hosts: localhost #workstations # Target local machine Alt:`all`.
  ignore_unreachable: yes # Skip hosts that are not reachable.
  connection: local # Instructs Ansible to execute tasks directly on the controller machine, instead of using SSH.
  become: true # Enables privilege escalation (sudo).
  gather_facts: true # Collects detailed information about target systems to enable dynamic behavior in playbooks.

  # ROLES:
  roles:
    - role: workstation
      vars:
        user: tim
