# DEFAULTS --------------------------------------------------- #
# Defines default values that apply to all systems or can be overridden easily.
# Lowest in Ansible’s variable precedence.

user: "{{ ansible_user_id }}"
packages_install: [] # Define is case OS file definition is empty.
packages_remove: [] # Define is case OS file definition is empty.

flatpak_enabled: true
flatpak_remotes:
    - name: flathub
      url: https://flathub.org/repo/flathub.flatpakrepo
flatpak_install:
    # System ------------------------------------- #
    - name: com.github.tchx84.Flatseal # FlatSeal: Manage Flatpak permissions
    - name: com.mattjakeman.ExtensionManager # Gnome Extensions.
    # Web Browsers ------------------------------------- #
    - name: org.mozilla.firefox # Web Browser: Firefox
    - name: com.google.Chrome # Web Browser: Chrome
    # Image Editors ------------------------------------- #
    - name: com.jgraph.drawio.desktop # Draw IO: Design diagrams
    - name: org.gimp.GIMP # Gimp: Image editor
    # Coding ------------------------------------- #
    - name: org.kde.kate # Kate: Code
    - name: com.visualstudio.code # Visual Studio Code: https://github.com/flathub/com.visualstudio.code
    # RDP Clients ------------------------------------- #
    #- name: com.thincast.client # ThinCast: RDP client # Disabled in favour of 'freerdp' package.
    # Misc ------------------------------------- #
    - name: com.valvesoftware.Steam # Steam: Game manager
    - name: com.spotify.Client # Spotify: Music streaming
    - name: md.obsidian.Obsidian # Obsidian: Note taking app.
    - name: org.libreoffice.LibreOffice # Libre Office: Office suit.
