# CONFIG ------------------------------------------------- #

# Update package cache.
- name: Package_Cache_Update
  package:
      update_cache: yes

# APPLICATIONS ------------------------------------------------- #

- name: Packages_Install
  package:
      name: "{{ packages_install }}"
      state: present
      
- name: Packages_Remove
  package:
      name: "{{ packages_remove }}"
      state: absent
