flatpak_remotes:
    - name: flathub
      url: https://flathub.org/repo/flathub.flatpakrepo

apps_flatpak:
    - com.github.tchx84.Flatseal # FlatSeal: Manage Flatpak permissions
    - org.mozilla.firefox # Firefox: Web browser
    - com.thincast.client # ThinCast: RDP client
    - com.jgraph.drawio.desktop # Draw IO: Design diagrams
    - org.gimp.GIMP # Gimp: Image editor
    - org.kde.kate # Kate: Code editor
    - com.valvesoftware.Steam # Steam: Game manager
    - com.spotify.Client # Spotify: Music streaming
    - md.obsidian.Obsidian # Obsidian: Note taking app.
    - org.libreoffice.LibreOffice # Libre Office: Office suit.
