# VARIABLES --------------------------------------- #
# Define opinionated, OS-specific values.
# Use different package names if they differ between OS versions.

package_manager: dnf
packages_install:
    - traceroute
    - git
    - gh
    - nano
    - curl
    - net-tools
    - wget
    - azure-cli
    - terraform
    - terraform-ls
    - nmap
    - virt-manager
    - wireshark
    - vlc
    - freerdp
packages_remove:
    - gnome-tour # Gnome: Default tour app.
    - gnome-contacts # Gnome: Default contacts app.
    - showtime # Gnome: Default video player.
    - decibles # Gnome: Default audio player.
