# VARIABLES --------------------------------------- #
# Define opinionated, OS-specific values.
# Use different package names if they differ between OS versions.

package_manager: dnf
packages_install:
    - traceroute
    - git
    - gh
    - nano
    - curl
    - net-tools
    - wget
    - azure-cli
    - terraform
    - terraform-ls
    - nmap
    - virt-manager
    - wireshark
    - vlc
    - freerdp
    - powershell # Requires script to add repo.
    - waydroid
